name: linters
on: push

jobs:
  format:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: "1"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --prod

      - name: check for formatting
        run: npm run lint
