name: linters
on: push

jobs:
  format:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: "1"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: check for formatting
        run: npm run lint
